-- ============================================================
-- chat_turn : one row per question asked
-- ============================================================
--
-- Serves three jobs at once, which is why it is a single table rather than a
-- chat table plus a chart table:
--
--   1. The chart endpoint reads sql_text back off a stored turn to regenerate
--      a chart without re-running the whole pipeline.
--   2. The router reads the last few turns of a session to resolve follow-ups
--      like "now break that down by region".
--   3. It is the query-history feature listed under the assignment's bonuses.
--
-- The chart config lives here as JSONB rather than in its own table because
-- there is only ever one chart per turn - chart revision is out of scope, so
-- there is no history to model.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS chat_turn (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Groups turns into a conversation. Generated by the client; there are no
    -- accounts in this application, so nothing stronger is warranted.
    session_id   uuid        NOT NULL,

    question     text        NOT NULL,

    -- Which tool the router picked: sql, forecast, or direct. Stored because
    -- it is the single most useful field for explaining, after the fact, why
    -- a turn produced what it produced.
    mode         varchar(20) NOT NULL,

    -- The validated statement that actually executed. NULL on a forecast or
    -- direct turn, and NULL on a sql turn whose generated SQL never passed
    -- validation.
    sql_text     text,

    answer       text,

    -- The result set as returned to the frontend. Capped by the executor's
    -- row limit, so this stays small enough to store inline.
    row_json     jsonb,

    -- The ChartConfig the frontend rendered, or NULL when the result was not
    -- chartable or the chart branch failed.
    chart_config jsonb,

    -- The explainability payload: tables and columns the validator saw,
    -- filters applied, the resolved date window, and the row count. Section
    -- 4.4 of the spec asks for exactly this, and keeping it beside the answer
    -- means the panel can be rebuilt when a turn is reopened from history.
    explain_json jsonb,

    -- Populated instead of answer when the turn failed. Kept rather than
    -- discarded so the history view can show what went wrong.
    error        text,

    created_at   timestamptz NOT NULL DEFAULT now()
);

-- The router's "last 3 turns of this session" lookup, which runs on every
-- single question and is the only read this table serves on the hot path.
CREATE INDEX IF NOT EXISTS idx_chat_turn_session_created
    ON chat_turn (session_id, created_at DESC);
