"""Wire contracts.

The chart contract matters most: both the SQL path (chosen by the model) and
the forecast path (built in Python) produce this same ChartConfig, so the
frontend has exactly one renderer.
"""

from typing import Any, Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field

# Six types, not the thirteen the reference supports. Every question this
# dataset can answer is a trend, a comparison, or a composition, and each type
# dropped is a branch of validation that cannot go wrong.
ChartType = Literal["bar", "line", "area", "stacked_bar", "pie", "doughnut"]

ForecastLevel = Literal["overall", "category", "region"]
ForecastMethod = Literal["moving_average", "linear_regression"]


# ------------------------------------------------------------
# Requests
# ------------------------------------------------------------


class ChatRequest(BaseModel):
    question: str
    # Groups turns into a conversation so the router can resolve follow-ups.
    # Generated by the client; absent on the first turn.
    session_id: Optional[UUID] = None


class ChartRequest(BaseModel):
    """Regenerate the chart for a turn that already ran."""

    turn_id: UUID


class ForecastRequest(BaseModel):
    level: ForecastLevel = "overall"
    # The category or region to forecast. Ignored when level is overall.
    key: Optional[str] = None
    horizon: int = Field(default=3, ge=1, le=12)
    method: ForecastMethod = "moving_average"


# ------------------------------------------------------------
# Router output
# ------------------------------------------------------------


class ForecastParams(BaseModel):
    level: ForecastLevel = "overall"
    key: Optional[str] = None
    horizon: int = Field(default=3, ge=1, le=12)
    method: ForecastMethod = "moving_average"

    # What the user actually named, before it was resolved to a level the data
    # can support. Carried so the answer can say "SKU CRAYON-0008 has three
    # orders, so this forecasts the CRAYON category instead" rather than
    # silently answering a different question.
    requested_sku: Optional[str] = None


class RouteDecision(BaseModel):
    """The single structured output of the router call."""

    mode: Literal["sql", "forecast", "direct"]
    sql: Optional[str] = None
    forecast: Optional[ForecastParams] = None
    reason: str = ""


# ------------------------------------------------------------
# Charts
# ------------------------------------------------------------


class ChartConfig(BaseModel):
    chartType: ChartType
    title: str
    description: str = ""

    xKey: str
    yKeys: List[str]

    # A column whose values each become a series - the shape needed when the
    # same x value appears on several rows, once per category. Distinct from
    # yKeys, which are columns.
    seriesKey: Optional[str] = None

    stacked: bool = False
    insight: str = ""


class FullChartConfig(ChartConfig):
    data: List[Dict[str, Any]]
    headers: List[str]

    # date | number | category, per column. Sent so the frontend can build
    # filter controls without guessing a type from the values.
    columnKinds: Dict[str, str] = Field(default_factory=dict)


# ------------------------------------------------------------
# Responses
# ------------------------------------------------------------


class ExplainPayload(BaseModel):
    """
    Everything behind an answer, which section 4.4 of the spec requires be
    shown alongside it.
    """

    mode: str
    reason: str = ""
    sql: Optional[str] = None
    tables: List[str] = Field(default_factory=list)
    columns: List[str] = Field(default_factory=list)
    filters: str = ""
    group_by: List[str] = Field(default_factory=list)
    row_count: int = 0
    truncated: bool = False
    limit_injected: bool = False
    anchor_date: Optional[str] = None
    retries: int = 0
    method: Optional[str] = None


class TurnResponse(BaseModel):
    turn_id: UUID
    session_id: UUID
    question: str
    mode: str
    answer: str
    rows: List[Dict[str, Any]] = Field(default_factory=list)
    chart: Optional[FullChartConfig] = None
    explain: ExplainPayload
    error: Optional[str] = None
